# Generated by Django 5.1.5 on 2025-01-22 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('mystical_level', models.IntegerField(help_text='Select a mystical level from 0 (Skeptical) to 10 (Fortune Teller).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mystical Level')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Avatar URL')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Specialization')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
            },
        ),
    ]
