# Generated by Django 5.1.4 on 2025-01-04 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0005_suit_arcana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['suit', 'number'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='readingcard',
            options={'ordering': ['position'], 'verbose_name': 'Reading Card', 'verbose_name_plural': 'Reading Cards'},
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_type',
            field=models.CharField(choices=[('single_card', 'Single Card'), ('three_card_spread', 'Three-Card Spread'), ('celtic_cross_spread', 'Celtic Cross Spread'), ('love_spread', 'Love Spread'), ('career_path_spread', 'Career Path Spread'), ('relationship_spread', 'Relationship Spread'), ('horseshoe_spread', 'Horseshoe Spread')], default='single_card', max_length=20, verbose_name='Reading Type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='tarot_cards/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='keywords',
            field=models.CharField(help_text='Comma-separated keywords', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='reversed_meaning',
            field=models.TextField(verbose_name='Reversed Meaning'),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tarot.suit', verbose_name='Suit'),
        ),
        migrations.AlterField(
            model_name='card',
            name='upright_meaning',
            field=models.TextField(verbose_name='Upright Meaning'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='celestial_insight',
            field=models.TextField(blank=True, null=True, verbose_name='Celestial Insight'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='question',
            field=models.TextField(blank=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='readingcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot.card', verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='readingcard',
            name='interpretation',
            field=models.TextField(blank=True, verbose_name='Interpretation'),
        ),
        migrations.AlterField(
            model_name='readingcard',
            name='orientation',
            field=models.CharField(choices=[('upright', 'Upright'), ('reversed', 'Reversed')], max_length=10, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='readingcard',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='readingcard',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tarot.reading', verbose_name='Reading'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='arcana',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='minor', max_length=10, verbose_name='Arcana'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='color',
            field=models.CharField(default='#000000', help_text='Color code (e.g. #FF0000)', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
