# Generated by Django 5.1.4 on 2025-01-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_alter_card_options_alter_readingcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='celestial_insight',
            field=models.TextField(blank=True, default='', verbose_name='Celestial Insight'),
        ),
    ]
