# Generated by Django 5.1.5 on 2025-01-24 21:31

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
        ('tarot', '0008_readingcard_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suit',
            name='color',
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='reading',
            name='mentor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_readings', to='mentors.mentor', verbose_name='Mentor'),
        ),
    ]
